# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.5
notifications:
  email: true
# uncomment the following lines to override the default test script
script:
 - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
 - julia -e 'Pkg.clone("https://github.com/tbreloff/MetaPkg.jl"); import MetaPkg; MetaPkg.add("MetaLearn"); MetaPkg.checkout("MetaLearn")'
 - julia -e 'Pkg.clone(pwd()); Pkg.build("StochasticOptimization");  Pkg.test("StochasticOptimization"; coverage=true)'
